My solution for the titanic ml challenge

First I load training data from csv to data frame

In [15]:
import pandas as pd

df = pd.read_csv("./titanic/train.csv")

#df.shape
display(df.head(5))

#print("Survived females: ", ((df["Sex"] == "female") & (df["Survived"] == 1)).sum())
#print("Survived males: ", ((df["Sex"] == "male") & (df["Survived"] == 1)).sum())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Some data exploration, seeing how classes affected survivability and who exactly survived

In [16]:
data = []
for pclass in sorted(df["Pclass"].unique()):
    total = (df["Pclass"] == pclass).sum()
    total_males = ((df["Sex"] == "male") & (df["Pclass"] == pclass)).sum()
    total_females = ((df["Sex"] == "female") & (df["Pclass"] == pclass)).sum()

    survived = ((df["Pclass"] == pclass) & (df["Survived"] == 1))
    men_survived = ((df["Sex"] == "male") & survived).sum()
    female_survived = ((df["Sex"] == "female") & survived).sum()

    kids = ((df["Age"] < 18) & survived).sum()

    data.append({
        "Class": pclass,
        "Passengers": total,
        "Survived": survived.sum(),
        "Survived children": kids, 
        "Percentage (%)": survived.sum() / total * 100,
        "Survived men": men_survived,
        "Total men": total_males,
        "Survived females": female_survived,
        "Total Females": total_females
    })

summary = pd.DataFrame(data)
display(summary.style
        .format({"Percentage (%)": "{:.2f}%"})
        .hide(axis="index"))

Missing values

In [17]:
#df.shape

df.info()

print(df["Cabin"].isna().sum())
print(df["Age"].isna().sum())
print(df["Embarked"].isna().sum())

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
687
177
2

Missing values:
- cabin (687)
- age (177)
- Embarked (2)

I will skip Cabin column entirely for now, in future i will try to make it known/unknown and see if model improves

For age i will imputate the missing values with median age and also test model with age - known/unknown feature

Embarked - I will just fill this with the most popular port of embarkation present in dataset

Data will be filled based on training groups

Splitting data into training and testing split

In [18]:
from typing import cast

from pandas import DataFrame, Series
from sklearn.model_selection import train_test_split


X = df.drop(columns=["Cabin", "Survived"])
y = df["Survived"]

X_train, X_test, y_train, y_test = cast(
    tuple[DataFrame, DataFrame, Series, Series],
    train_test_split(X, y, test_size=0.2, random_state=42, stratify=y),
)

print(X_train.shape)
print(X_test.shape)

(712, 10)
(179, 10)

Baseline - dummy classifier with most_frequent strategy so it will just spit the most frequent class in our dataset as its prediction. This is my baseline model which i will compare to my Logistic Regression

In [19]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

dummy = DummyClassifier(strategy="most_frequent")

dummy.fit(X_train, y_train)

print("Classes:", dummy.classes_)
print("Class distribution:")
print(y_train.value_counts(normalize=True))

y_train_pred = dummy.predict(X_train)

accuracy = accuracy_score(y_train, y_train_pred)
precision = precision_score(y_train, y_train_pred, zero_division=0)
recall = recall_score(y_train, y_train_pred)
f1 = f1_score(y_train, y_train_pred)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall : ", recall)
print("F1: ", f1)

Classes: [0 1]
Class distribution:
Survived
0    0.616573
1    0.383427
Name: proportion, dtype: float64
Accuracy:  0.6165730337078652
Precision:  0.0
Recall :  0.0
F1:  0.0

Cross validation to see how our dummy performs on different data

In [20]:
from sklearn.model_selection import cross_val_score


scores = cross_val_score(dummy, X_train, y_train, cv=5, scoring="accuracy")
print("CV accuracy scores: ", scores)
print("CV mean accuracy: ", scores.mean())

CV accuracy scores:  [0.61538462 0.61538462 0.61267606 0.61971831 0.61971831]
CV mean accuracy:  0.6165763813651137

Now I want to classify my features into numeric and categorical features because I want to preprocess them first to fill blank values

In [22]:
numeric_features = ["Age", "Fare", "SibSp", "Parch"]

categorical_features = ["Pclass", "Sex", "Embarked"]

features = numeric_features + categorical_features

X_train_selected = X_train[features]

#X_train_selected.shape
X_train_selected.head(5)

      Age      Fare  SibSp  Parch  Pclass     Sex Embarked
692   NaN   56.4958      0      0       3    male        S
481   NaN    0.0000      0      0       2    male        S
527   NaN  221.7792      0      0       1    male        S
855  18.0    9.3500      0      1       3  female        S
801  31.0   26.2500      1      1       2  female        S

Now i want to imputate my numeric features

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
#
#age_imputer = SimpleImputer(strategy="median")
#
#age_imputer.fit(X_train_selected[["Age"]])
#
##age_imputer.statistics_ # Median value of the age
#
#ages_transformed = age_imputer.transform(X_train_selected[["Age"]])
#
#print(ages_transformed)



numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

[[28.5 ]
 [28.5 ]
 [28.5 ]
 [18.  ]
 [31.  ]
 [21.  ]
 [26.  ]
 [28.5 ]
 [28.5 ]
 [31.  ]
 [56.  ]
 [21.  ]
 [28.5 ]
 [56.  ]
 [21.  ]
 [33.  ]
 [21.  ]
 [28.5 ]
 [43.  ]
 [28.5 ]
 [30.  ]
 [32.  ]
 [28.5 ]
 [19.  ]
 [24.  ]
 [45.  ]
 [23.  ]
 [42.  ]
 [39.  ]
 [16.  ]
 [28.5 ]
 [66.  ]
 [28.  ]
 [51.  ]
 [47.  ]
 [18.  ]
 [36.  ]
 [30.  ]
 [22.  ]
 [28.5 ]
 [25.  ]
 [28.5 ]
 [32.  ]
 [28.5 ]
 [19.  ]
 [52.  ]
 [71.  ]
 [32.  ]
 [19.  ]
 [28.5 ]
 [22.  ]
 [50.  ]
 [ 4.  ]
 [36.  ]
 [19.  ]
 [30.  ]
 [28.5 ]
 [30.  ]
 [21.  ]
 [30.  ]
 [18.  ]
 [19.  ]
 [38.  ]
 [10.  ]
 [28.5 ]
 [29.  ]
 [28.5 ]
 [28.  ]
 [39.  ]
 [ 2.  ]
 [30.  ]
 [25.  ]
 [14.  ]
 [35.  ]
 [17.  ]
 [28.5 ]
 [18.  ]
 [23.  ]
 [50.  ]
 [21.  ]
 [58.  ]
 [ 3.  ]
 [13.  ]
 [57.  ]
 [16.  ]
 [28.5 ]
 [60.  ]
 [22.  ]
 [30.  ]
 [17.  ]
 [25.  ]
 [27.  ]
 [36.  ]
 [28.5 ]
 [28.5 ]
 [29.  ]
 [30.  ]
 [28.5 ]
 [51.  ]
 [16.  ]
 [28.5 ]
 [ 1.  ]
 [22.  ]
 [28.5 ]
 [ 7.  ]
 [28.5 ]
 [28.5 ]
 [33.  ]
 [ 7.  ]
 [32.  ]
 [50.  ]
 [59.  ]
 [28.  ]
 [28.5 ]
 [60.  ]
 [17.  ]
 [32.5 ]
 [21.  ]
 [ 3.  ]
 [19.  ]
 [24.  ]
 [18.  ]
 [49.  ]
 [41.  ]
 [30.  ]
 [59.  ]
 [ 4.  ]
 [28.5 ]
 [51.  ]
 [45.  ]
 [18.  ]
 [28.5 ]
 [28.5 ]
 [28.  ]
 [55.5 ]
 [24.  ]
 [28.5 ]
 [28.5 ]
 [28.5 ]
 [28.5 ]
 [29.  ]
 [58.  ]
 [26.  ]
 [44.  ]
 [28.5 ]
 [32.  ]
 [26.  ]
 [16.  ]
 [19.  ]
 [28.5 ]
 [48.  ]
 [28.5 ]
 [ 9.  ]
 [35.  ]
 [12.  ]
 [31.  ]
 [27.  ]
 [43.  ]
 [30.5 ]
 [34.  ]
 [28.5 ]
 [23.  ]
 [24.  ]
 [39.  ]
 [24.  ]
 [28.5 ]
 [ 0.75]
 [34.  ]
 [23.  ]
 [42.  ]
 [28.5 ]
 [22.  ]
 [ 0.83]
 [28.5 ]
 [52.  ]
 [17.  ]
 [49.  ]
 [44.  ]
 [ 6.  ]
 [64.  ]
 [18.  ]
 [19.  ]
 [26.  ]
 [43.  ]
 [28.5 ]
 [23.  ]
 [16.  ]
 [36.  ]
 [22.  ]
 [19.  ]
 [28.5 ]
 [47.  ]
 [40.  ]
 [20.  ]
 [36.  ]
 [18.  ]
 [18.  ]
 [32.  ]
 [33.  ]
 [35.  ]
 [64.  ]
 [52.  ]
 [24.  ]
 [61.  ]
 [24.  ]
 [43.  ]
 [34.  ]
 [63.  ]
 [24.  ]
 [38.  ]
 [21.  ]
 [45.  ]
 [16.  ]
 [20.  ]
 [28.5 ]
 [41.  ]
 [30.  ]
 [29.  ]
 [ 3.  ]
 [ 3.  ]
 [54.  ]
 [28.  ]
 [36.  ]
 [48.  ]
 [31.  ]
 [26.  ]
 [28.5 ]
 [ 0.42]
 [25.  ]
 [28.5 ]
 [38.  ]
 [28.5 ]
 [28.5 ]
 [15.  ]
 [35.  ]
 [28.5 ]
 [24.  ]
 [36.  ]
 [22.  ]
 [50.  ]
 [28.5 ]
 [45.5 ]
 [33.  ]
 [19.  ]
 [18.  ]
 [16.  ]
 [28.5 ]
 [28.5 ]
 [48.  ]
 [22.  ]
 [29.  ]
 [28.5 ]
 [38.  ]
 [44.  ]
 [ 3.  ]
 [18.  ]
 [18.  ]
 [28.5 ]
 [ 2.  ]
 [35.  ]
 [74.  ]
 [31.  ]
 [28.5 ]
 [56.  ]
 [26.  ]
 [32.  ]
 [28.5 ]
 [40.  ]
 [27.  ]
 [28.5 ]
 [38.  ]
 [ 1.  ]
 [28.5 ]
 [28.5 ]
 [ 0.67]
 [28.5 ]
 [ 2.  ]
 [18.  ]
 [51.  ]
 [29.  ]
 [49.  ]
 [24.  ]
 [31.  ]
 [45.  ]
 [32.  ]
 [18.  ]
 [44.  ]
 [47.  ]
 [36.5 ]
 [30.  ]
 [27.  ]
 [29.  ]
 [71.  ]
 [52.  ]
 [43.  ]
 [22.  ]
 [28.5 ]
 [28.5 ]
 [26.  ]
 [25.  ]
 [28.5 ]
 [31.  ]
 [45.  ]
 [22.  ]
 [49.  ]
 [22.  ]
 [ 4.  ]
 [29.  ]
 [34.  ]
 [48.  ]
 [27.  ]
 [54.  ]
 [28.5 ]
 [19.  ]
 [22.  ]
 [45.5 ]
 [28.5 ]
 [23.  ]
 [30.  ]
 [28.5 ]
 [34.  ]
 [31.  ]
 [28.5 ]
 [40.  ]
 [28.5 ]
 [32.  ]
 [20.  ]
 [27.  ]
 [32.5 ]
 [44.  ]
 [23.  ]
 [34.  ]
 [32.  ]
 [ 4.  ]
 [ 2.  ]
 [28.5 ]
 [25.  ]
 [24.  ]
 [21.  ]
 [31.  ]
 [54.  ]
 [33.  ]
 [23.  ]
 [19.  ]
 [65.  ]
 [28.5 ]
 [42.  ]
 [18.  ]
 [27.  ]
 [54.  ]
 [28.5 ]
 [47.  ]
 [11.  ]
 [21.  ]
 [29.  ]
 [39.  ]
 [39.  ]
 [36.  ]
 [17.  ]
 [28.5 ]
 [11.  ]
 [47.  ]
 [28.5 ]
 [38.  ]
 [28.5 ]
 [19.  ]
 [48.  ]
 [28.5 ]
 [28.5 ]
 [40.  ]
 [31.  ]
 [ 8.  ]
 [26.  ]
 [24.  ]
 [22.  ]
 [ 4.  ]
 [45.  ]
 [42.  ]
 [32.  ]
 [51.  ]
 [14.5 ]
 [28.5 ]
 [27.  ]
 [28.5 ]
 [ 8.  ]
 [42.  ]
 [40.  ]
 [ 5.  ]
 [30.  ]
 [28.5 ]
 [ 4.  ]
 [ 0.83]
 [28.  ]
 [20.  ]
 [28.5 ]
 [28.5 ]
 [17.  ]
 [28.5 ]
 [29.  ]
 [35.  ]
 [ 6.  ]
 [19.  ]
 [21.  ]
 [20.  ]
 [ 7.  ]
 [39.  ]
 [26.  ]
 [45.  ]
 [33.  ]
 [ 2.  ]
 [28.5 ]
 [26.  ]
 [32.  ]
 [35.  ]
 [28.  ]
 [39.  ]
 [28.  ]
 [37.  ]
 [28.5 ]
 [ 4.  ]
 [23.  ]
 [38.  ]
 [25.  ]
 [29.  ]
 [54.  ]
 [24.  ]
 [28.  ]
 [28.5 ]
 [14.  ]
 [41.  ]
 [28.5 ]
 [50.  ]
 [28.5 ]
 [21.  ]
 [22.  ]
 [24.  ]
 [21.  ]
 [51.  ]
 [24.  ]
 [19.  ]
 [22.  ]
 [61.  ]
 [28.5 ]
 [19.  ]
 [28.5 ]
 [22.  ]
 [28.  ]
 [54.  ]
 [41.  ]
 [28.5 ]
 [28.5 ]
 [21.  ]
 [40.  ]
 [36.  ]
 [29.  ]
 [15.  ]
 [40.5 ]
 [29.  ]
 [33.  ]
 [19.  ]
 [35.  ]
 [18.  ]
 [18.  ]
 [28.5 ]
 [28.5 ]
 [28.5 ]
 [21.  ]
 [28.5 ]
 [39.  ]
 [20.  ]
 [58.  ]
 [49.  ]
 [ 5.  ]
 [39.  ]
 [17.  ]
 [65.  ]
 [28.5 ]
 [28.5 ]
 [21.  ]
 [31.  ]
 [32.  ]
 [39.  ]
 [20.  ]
 [34.  ]
 [47.  ]
 [36.  ]
 [21.  ]
 [28.5 ]
 [28.5 ]
 [30.  ]
 [28.5 ]
 [28.5 ]
 [33.  ]
 [30.  ]
 [ 1.  ]
 [20.  ]
 [34.  ]
 [45.  ]
 [36.  ]
 [39.  ]
 [20.  ]
 [34.5 ]
 [28.  ]
 [28.5 ]
 [28.5 ]
 [10.  ]
 [ 9.  ]
 [28.5 ]
 [20.5 ]
 [28.5 ]
 [36.  ]
 [28.5 ]
 [28.5 ]
 [20.  ]
 [22.  ]
 [39.  ]
 [37.  ]
 [48.  ]
 [23.  ]
 [28.5 ]
 [70.  ]
 [32.  ]
 [16.  ]
 [21.  ]
 [28.5 ]
 [42.  ]
 [24.  ]
 [22.  ]
 [40.  ]
 [ 0.92]
 [33.  ]
 [18.  ]
 [28.  ]
 [37.  ]
 [ 5.  ]
 [13.  ]
 [27.  ]
 [38.  ]
 [42.  ]
 [ 3.  ]
 [28.  ]
 [50.  ]
 [51.  ]
 [28.5 ]
 [26.  ]
 [28.5 ]
 [24.  ]
 [42.  ]
 [42.  ]
 [28.5 ]
 [36.  ]
 [19.  ]
 [28.5 ]
 [65.  ]
 [15.  ]
 [28.5 ]
 [46.  ]
 [28.  ]
 [50.  ]
 [19.  ]
 [28.5 ]
 [25.  ]
 [62.  ]
 [27.  ]
 [35.  ]
 [28.5 ]
 [42.  ]
 [28.5 ]
 [28.5 ]
 [24.  ]
 [24.  ]
 [ 4.  ]
 [28.  ]
 [18.  ]
 [27.  ]
 [28.5 ]
 [14.  ]
 [28.  ]
 [22.  ]
 [37.  ]
 [47.  ]
 [28.5 ]
 [28.  ]
 [36.  ]
 [20.  ]
 [55.  ]
 [28.5 ]
 [22.  ]
 [57.  ]
 [29.  ]
 [26.  ]
 [28.5 ]
 [39.  ]
 [32.  ]
 [30.  ]
 [38.  ]
 [28.5 ]
 [18.  ]
 [24.  ]
 [ 4.  ]
 [22.  ]
 [28.5 ]
 [23.  ]
 [18.  ]
 [28.5 ]
 [33.  ]
 [ 8.  ]
 [22.  ]
 [36.  ]
 [25.  ]
 [19.  ]
 [28.5 ]
 [36.  ]
 [23.  ]
 [29.  ]
 [ 1.  ]
 [35.  ]
 [29.  ]
 [44.  ]
 [36.  ]
 [28.5 ]
 [28.5 ]
 [21.  ]
 [16.  ]
 [ 6.  ]
 [32.  ]
 [38.  ]
 [26.  ]
 [54.  ]
 [28.5 ]
 [40.  ]
 [42.  ]
 [28.  ]
 [35.  ]
 [18.  ]
 [18.  ]
 [ 9.  ]
 [36.  ]
 [ 2.  ]
 [25.  ]
 [54.  ]
 [ 9.  ]
 [80.  ]
 [40.  ]
 [41.  ]
 [24.  ]
 [22.  ]
 [17.  ]
 [45.  ]
 [20.  ]
 [52.  ]
 [35.  ]
 [30.  ]
 [28.5 ]
 [38.  ]
 [28.5 ]
 [39.  ]
 [31.  ]
 [22.  ]
 [20.  ]
 [22.  ]
 [26.  ]
 [15.  ]
 [32.  ]
 [30.  ]
 [34.  ]
 [28.5 ]
 [ 1.  ]
 [28.  ]
 [30.  ]
 [22.  ]
 [21.  ]
 [36.  ]
 [40.  ]
 [ 1.  ]
 [40.  ]
 [28.  ]
 [40.  ]
 [28.5 ]
 [27.  ]
 [24.  ]
 [ 5.  ]
 [34.  ]
 [23.  ]
 [70.5 ]
 [17.  ]
 [16.  ]
 [19.  ]
 [25.  ]
 [25.  ]
 [42.  ]
 [21.  ]
 [28.5 ]
 [28.5 ]
 [15.  ]
 [45.  ]
 [28.5 ]
 [25.  ]
 [33.  ]
 [28.  ]
 [32.  ]
 [26.  ]
 [37.  ]
 [50.  ]
 [50.  ]
 [28.5 ]
 [34.  ]
 [28.5 ]
 [35.  ]
 [48.  ]
 [47.  ]
 [28.5 ]]